# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiLoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(400, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(LoginForm)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 9, 381, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.userLoginBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.userLoginBtn.setObjectName("userLoginBtn")
        self.gridLayout.addWidget(self.userLoginBtn, 1, 0, 1, 1)
        self.workerLoginBtn = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.workerLoginBtn.setObjectName("workerLoginBtn")
        self.gridLayout.addWidget(self.workerLoginBtn, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "Вход в систему"))
        self.userLoginBtn.setText(_translate("LoginForm", "Как Пользователь"))
        self.workerLoginBtn.setText(_translate("LoginForm", "Как Работник музея"))
        self.label.setText(_translate("LoginForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Добро пожаловать!</span></p><p align=\"center\"><span style=\" font-size:14pt;\">Как войти в систему?</span></p></body></html>"))
